---
title: Курс "Data Science"
description: Материалы курса 
---
 

```{r setup, include=FALSE}
library(knitr)
opts_chunk$set(echo = FALSE)
```



# **Материалы 2020-2021 учебного года** 

## **Часть 1.** Первые шаги 

Надо будет установить себе на компьютер две программы:

1. Собственно **язык R** https://cran.r-project.org/bin/windows/base/
2. Среду **Rstudio**, которая существенно облегчает и ускоряет работу с R. https://www.rstudio.com/products/rstudio/download/

После того, как это сделали, откройте RStudio и попытайтесь разобраться тем, как это работает самостоятельно. Для этого используте вот эту [презентацию](https://varmara.github.io/linmodr/01_intro_to_r.html)


**Задание №1**

Если вы в этом разобрались с тем, как это работает, то установите себе пакет ggplot2. Попробуйте самостоятельно поработать с ним. Для этого вы можете воспользоваться простой [презентацией, подготовленной Аленой и Ренатой](https://drive.google.com/file/d/1Qu04vLwldakmHmOEwOzBOKvohrj3J0U5/view?usp=sharing).
Нарисуйте самостоятельно какой-нибудь график.


**Задание №2**


Если вы вы этом разобрались, то вы сможете выполнить следующее задание. Посмотрите [видео фрагмент с рассказом о том, что такое Rmarkdown](https://drive.google.com/file/d/1CCwBc_rlF77W1R_-0tCWVFY4TsX6fTG6/view?usp=sharing). 

*NB! Там в конце косяк из-за того, что программа видеозахвата экрана понимает под экраном только то, с чего она начала работать. Увы, это не обойти. Так что пытайтесь сами. Жду ваших ответов до 23:59 понедельника 19 октября.*   


- [Файл для скачивания]("data/Chemtred 2019.xlsx")






## **Часть 2.** Создаем сложный html-документ 

- [файл, который мы будем создавать](data/Сложный файл.html) 

- [Данные файл 1](data/Astfood_Length.csv)
- [Данные файл 2](data/Astfood_2019.csv)
- [Данные файл 3](data/Astfood_Asterias_2019.csv)


**Задание №1.**

Просмотрите [это видео](https://drive.google.com/file/d/10iAsdgHHtOssLAvUVCwPDajsz69QqjLe/view?usp=sharing), в нем вы найдете историю про то, как можно создать довольно сложный html-документ с использованием языка R-markdown. Поскольку это мы уже проделывали при очной встрече, то все, что вы увидите в этом видео - это будет повторение. На всякий случай вот [тот RMD-файл, который получился в данном видео](data/My_html.Rmd).  


<br>

**Задание №2.**

Вам нужно будет создать такой rmd-файл, который после его нитриния произвел бы на свет [вот такой html-документ](data/Eiler.html).


<br>

## **Часть 3.** Создаем презентацию в формате html-документа  

**Задание №3.**

Вам нужно будет создать вот такой [html-документ](data/Khaitov_presentation_dept_Hydrobiology_simplified.html), пользуясь материалами, которые нахрдятся в файле[ "Constructor.zip"](data/Constructor.zip)


<br>
<br>



# **Материалы предыдущего учебного года** 

## **Часть 1.** Первые шаги 

## Что надо сделать в первую очередь

Поскольку все находятся на разных уровнях своего онтогенеза, то тем, кто вообще еще ничего не знает, предлагается пройти курс молодого бойца, освоив материалы следующей презентации. Бойцам менее молодым тоже рекомендуется просмотреть материалы этой презентации.

https://varmara.github.io/linmodr/01_intro_to_r.html

Перед тем, как ее проходить надо будет установить себе на компьютер две программы:

1. Собственно **язык R** https://cran.r-project.org/bin/windows/base/
2. Среду **Rstudio**, которая существенно облегчает и ускоряет работу с R. https://www.rstudio.com/products/rstudio/download/



## **Часть 2.** Учимся работать с простейшими кодами
Ниже вы найдете код, который мы написали в предыдущем занятии. 

Теперь мы знаем как присваивать значения переменным, как написать пользовательскую функцию, что такое векторы и как проводится обращение к элементам векторов.

[Вот код](Data_science/My_firs_steps/my_first_script.R)

**Домашнее задание**

Часть 1. Мы решили, что команда R_азруштелей легенд в этом году займется выяснением зависят ли оценки учащихся от погодных условий. Поэтому, используя данные электронных дневников как можно большего количества своих одноклассников (за прошлые года и можно за этот год) создайте базу данных, которая включала бы следующие поля: Дата, предмет, оценка, класс, Имя ученика (можно номер вместо учеников номера). Чем больше людей будет отраженно в базе, тем надежнее будут выводы. Свои базы данных в экселевском формате присылайте мне по почте до вечера вторника 12 февраля. 

Часть 2. Поставьте себе следующие пакеты. MASS, ggplot2, car, ISwR, dplyr. Про то как ставить пакеты разберитесь самостоятельно.

# **Часть 3.** Визуализация данных

Вот код который мы породили на занятии

[Вот код](Data_science/My_firs_steps/my_first_script.R)


**Домашнее задание**
1. Доработать код так, чтобы он цветом отражал вес матери от желтого (минимум) до красного (максимум).   
2. Убрать легенду с графика совсем.   
4. Марина добивает базу по оценкам.   
5. Все остальные ищут данные по метеоусловиям за сентябрь-декабрь 2018 (совет: загляниет на rp5). На основе этих данных создаете базу данных по погодным условиям.   


## **Часть 4.** Визуализация данных с простейшей статистической обработкой 

Марина молодец! Она добила базу данных для нашего проекта Rазрушителей легенд. Скачайте файл. Дорабатывать будем вместе. 

[Вот файл](Data_science/My_firs_steps/data/credits.xlsx)


**Домашнее задание от 6.03.2019**
Используя данные из базы данных по оценкам, которая находится в [этом файле](Data_science/My_firs_steps/data/credits.xlsx), нужно будет создать два файла в формате CSV. Первый файл с оценкам за сентябрь, второй -- с оценками за октябрь. В коде, который мы создали лежит пример визуализации оценок за сентябрь с помощью бокс-плотов. Нужно будет построить похожий график, но так, чтобы данные за сентябрь и за октябрь находились на одном рисунке на двух разных фасетках. [Вот код который мы написали](Data_science/My_firs_steps/my_first_script.R).


## **Часть 5.** Учимся манипулировать данными 

Будем изучать методы фильтрации и соединения разнородных данных.

Для работы надо будет скачать данные по гендерной принадлежности изчаемой группы учеников.

[Вот эти данные](Data_science/My_firs_steps/data/gender.csv).

Кроме того, я сам за вас (вот нехорошие...) скачал данные по погоде в СПб за интересующий нас срок.


[Вот эти данные](Data_science/My_firs_steps/data/weather.xls).


# **Часть 6.** Учимся оценивать параметры генеральной совокупности по выборкам

[Вот код который мы написали на прошлом занятии](Data_science/My_firs_steps/my_first_script.R).

Теперь мы знаем, что если величина в генеральной совокупности подчиняется нормальному распределению, то есть только два параметра, которые надо знать, чтобы понять все про эту генеральную совокупность: среднее значение и дисперсия. Но они нам неизвестны и мы используем выборки небольшого объема для их оценки. 
По выборке мы вычислем:
- Среднее выборочное.
- Стандартное отклонение.
- Стандартную ошибку среднего. 

Для того, чтобы пощупать своими руками то, что эти выборочные показатели означают, вам предлагается решить следующую задачку.

### Домашнее задание на среду

Как известно, созданием разумных существ в Средиземье занимались все, кому не лень. Да и сама по себе эволюция там за четыре эпохи как-никак шла... Короче, решил Эру Илуватар наконец разобраться сколько всего рас обитает в некогда созданной им Арде. И заслал он своего верного майар Пенальда Серобуромалинового в Средиземье и велел ему разобраться в вопросе и предоставить технический отчет. Долго бродил Пенальд по просторам континента и у всех существ, с которыми он имел дело, он измерял их рост и длину ушей. Все это он добросовестно свел в [csv-файл](Data_science/My_firs_steps/data/arda.csv). Помогите Пенальду ответить на следующие вопросы:
1.Сколько всего рас обтитает в Средиземье.
2.Какие именно значения параметров имели ввиду создатели тех или иных рас, когда творили свих питомцев.    



