---
title: "Станция «Экология»"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

### С кем вы там встретитесь? 

Если вы посетите эту станцию, то вам представится возможность вступить в поединок с преподавателями и научными  сотрудниками, работающими в СПбГУ и СПбГДТЮ. Люди, с которыми вы пообщаетесь – это практикующие паразитологи, геоботаники, гидробиологи и специалисты по экологии наземных животных. 

### О чем и как вас будут спрашивать? 

Готовьтесь к тому, что на этой станции самое главное – это не вызубренные знания из учебника, а умение ими пользоваться. Вам предложат порассуждать на какие-нибудь темы (могут предложить даже вытянуть билет), но содержание разговора будет зависеть исключительно от вашей активности. Чем активнее вы выдвигаете те или иные решения, чем шире привлекаете оригинальные примеры, тем больше вероятность, что беседа будет интересной. 

### Кому не стоит приходить на станцию «Экология»? 

Тем, кто всерьез использует газетные штампы вроде «экология культуры», «здесь плохая экология», «экологи занимаются охраной окружающей среды»  и т.п. 

### О чем спрашивают на станции? 

О научных аспектах взаимоотношений организмов друг с другом и со средой их обитания, о закономерностях структуры и динамики надорганизменных систем (популяций, сообществ, биосферы).
Вот примерный список ключевых слов, которые могут помочь вам сориентироваться в предмете, о котором пойдет речь на станции.


### Экологический глоссарий 

Аутоэкология, Абиотический фактор, Автотрофы, Агрегация, Агроценоз, Адаптация, Аменсализм, Антропогенный фактор, Биогеоценоз, Биомасса, Биосфера, Биотический фактор, Биотоп, Видовое богатство, Видовое разнообразие, Возрастная структура популяции, Вторичная продукция, Вторичная сукцессия, Гетеротрофы, Демэкология, Детрит, дыхание сообщества, Емкость среды, Закон Либиха, Закон Шелфорда, Зона летали, Зона оптимума, Зона пессимума, Иммиграция, Климаксное сообщество (климакс), Комменсализм, Конкуренция, Консументы, Лимитирующий фактор, местообитание, Мутуализм, Нейтрализм, Паразитизм, Первичная продукция, Первичная сукцессия, Плотность популяции, Половая структура популяции, Популяционные волны (волны жизни), Популяционный коллапс, Популяция, Принцип Гаузе, Продуценты, Протокооперация, Редуценты, Симбиоз, Симбионт, Синойкия, Синэкология, Сообщество, Стенобионты, Сукцессия, Трофическая цепь, Трофический уровень, Удельная рождаемость, Удельная смертность, Численность популяции, Чистая первичная продукция, Эврибионты, Экологическая ниша, Экологическая пирамида, Экологический фактор, Экология, Экосистема, Эмиграция.

Если хотя бы половина из этих слов вам знакома, то смело приходите на станцию «Экология» - получите настоящее удовольствие. 

### Тест для проверки своих знаний в области экологии

[**Пройди меня...**](https://docs.google.com/forms/d/e/1FAIpQLSed0_PqMiWj1xr9nyP79QQdclkvZp-Tk5zhOlS_423UWJKIhg/viewform?usp=sf_link)


### Что почитать?

Электронный учебник «Биология», раздел «Экология». http://ebio.ru/index-5.html

Не поленитесь почитать школьный учебник.   
Общая биология. 10-11 класс. Каменский А.А., Криксунов Е.А., Пасечник В.В. М.: Дрофа, 2005. - 367 с.
Не так уж он и плох.  


Дажо, Р. Основы экологии / Р. Дажо; пер с франц. В. И. Назарова; под ред. В. В. Алпатова. - М.: Прогресс, 1975. - 415 с.

Экология. Особи популяции и сообщества. В 2-х томах. М. Бигон, Дж. Харпер, К. Таунсенд. М.: Мир, 1989. Т.1- 667с.; Т.2 - 477с.

Нинбург Е.А. Введение в общую экологию. Изд. КМК. М. 2005. 138 с.

